#include "enclave_t.h"
/**
 * Include the header file generated by cgo
 * to try to invoke golang logic in the enclave file
 */
#include "_cgo_export.h"

int test(int a, int b) {
    GoInt result;
    result = Addition((GoInt)a, (GoInt)b);
    int c_type_result = (int)result;
    return c_type_result;
}
